# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maki < Formula
  desc "Maki, Make but interactive."
  homepage "https://github.com/lorenzophys/maki"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lorenzophys/maki/releases/download/v0.1.0/maki_Darwin_arm64.tar.gz"
      sha256 "9be09920ff2023220ebea45d05285db7a99474511846e05552ef0b211e5e9930"

      def install
        bin.install "maki"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lorenzophys/maki/releases/download/v0.1.0/maki_Darwin_x86_64.tar.gz"
      sha256 "73c9821a81690a128aca0f2212f9ee5183c512bf3ac0bbf6a0f11e1bfa41e8e3"

      def install
        bin.install "maki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lorenzophys/maki/releases/download/v0.1.0/maki_Linux_arm64.tar.gz"
      sha256 "ff9fa8e7f30c27ca9c9157b708eff6356e9f20530e5560ab5e3d26e59d773961"

      def install
        bin.install "maki"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lorenzophys/maki/releases/download/v0.1.0/maki_Linux_x86_64.tar.gz"
      sha256 "599d4ae66aa44a8d297d945e3de2737e93b64aafa8b6dc7ec435841cee169b1a"

      def install
        bin.install "maki"
      end
    end
  end
end
